[package]
name = "module"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
publish = false

[dependencies]
serde = { version = "1.0.195", features = ["derive", "alloc", "rc"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
