[workspace]
members = [
  "crates/utils",
  "crates/project",
  "crates/opencascade-sys",
  "crates/occara",
  "crates/icara",
  "crates/computegraph",
  "crates/computegraph_macros",
  "crates/cadara",
  "crates/module",
]
resolver = "2"
