[workspace]
members = [
  "crates/utils",
  "crates/project",
  "crates/opencascade-sys",
  "crates/occara",
  "crates/computegraph",
]

[package]
name = "cadara"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
