[package]
name = "computegraph"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
publish = false

[dependencies]
thiserror = "1.0.60"
computegraph_macros = { path = "../computegraph_macros" }
dyn-clone = "1.0.17"

[dev-dependencies]
anyhow = "1.0.86"
