[package]
name = "computegraph_macros"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
name = "computegraph_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "*"
syn = { version = "*", features = ["extra-traits", "full"] }
proc-macro2 = "*"
