[package]
name = "cadara"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
iced = "0.12.1"
tracing-subscriber = "0.3.18"
viewport = { path = "../viewport" }
computegraph = { path = "../computegraph" }
workspace = { path = "../workspace" }
modeling-workspace = { path = "../modeling-workspace" }
modeling-module = { path = "../modeling-module" }
module = { path = "../module" }
project = { path = "../project" }
