name: Build and Test

on:
  pull_request:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Cache OpenCASCADE
        uses: actions/cache@v4
        with:
          path: |
            crates/opencascade-sys/occt_build
            crates/opencascade-sys/occt_source
          key: opencascade-${{ runner.os }}-${{ hashFiles('**/occt_commit_hash.lock') }}
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests
        run: cargo test --verbose --workspace
