[package]
name = "occara"
description = "High-level Rust bindings to the OpenCASCADE B-Rep library"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx = "0.27.0"
cxx = "1.0.117"
walkdir = "2.4.0"

[build-dependencies]
opencascade-sys = { path = "../opencascade-sys" }
cxx-build = { version = "1.0.118", features = ["parallel"] }
walkdir = "2.4.0"
autocxx-build = "0.27.0"
miette = { version = "5", features = ["fancy"] }

[dev-dependencies]
ordered-float = "4.2.0"
